# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Derivv
email: levi@hatchmatter.com
description: >- # this means to ignore newlines until "baseurl:"
  Derivv is a browser based image processing website
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://derivv.com" # the base hostname & protocol for your site, e.g. http://example.com
port: 4567
twitter_username: jekyllrb
github_username: jekyll

source: _src

plugins:
  - jekyll/vite
  - jekyll-feed
  - jekyll-multiple-languages-plugin
  - jekyll-paginate

languages: ["en", "es"]

exclude:
  - bin
  - config
  - vite.config.ts
  - package.json
  - package-lock.json
  - tmp
  - Procfile.dev
  - exe
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Rakefile
  - README.md

# Custom variables:
env:
  JEKYLL_ENV: development

# Hyde Theme settings
# Permalinks
permalink: pretty
paginate_path: "/blog/page:num/"

paginate: 5
